services:
    laravel.test:
        build:
            context: "./vendor/laravel/sail/runtimes/8.3"
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: "sail-8.3/app"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-81}:80"
            - "${VITE_PORT:-5174}:${VITE_PORT:-5174}"
            - '9001:9001'
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
            - "./xdebug.ini:/etc/php/8.3/cli/conf.d/20-xdebug.ini"
        networks:
            - themplus-network
        depends_on:
            - mysql_themplus_back
    ngrok:
        image: ngrok/ngrok:latest
        container_name: themplus_ngrok
        restart: unless-stopped
        ports:
            - "4040:4040"
        environment:
            NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
        command: >
            http laravel.test:80
            --domain=${NGROK_DOMAIN}
        networks:
            - themplus-network
        depends_on:
            - laravel.test
    mysql_themplus_back:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3307}:3306"
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "sail-mysql:/var/lib/mysql"
            - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - themplus-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s
networks:
    themplus-network:
        driver: bridge
        external: true
volumes:
    sail-mysql:
        driver: local
